name: CD - Web - prod

on:
  push:
    workflow_dispatch:
    # Pattern matched against refs/tags
    tags:
      - 'web-v*' # Push events to every tag not containing /
      - 'docs-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: curl -X POST -d {} ${{ secrets.WEB_DEPLOY_HOOK }}
